profiling:
  mode: "%env(app.mode)%"

  profiler:
    enabled: true                             # Enable profiler work

    # List of pages to be profiled, by default, if the list is empty,
    # all open pages will be profiled, except for service pages
    profilingPages: {}

    # Profiler access security
    security:
      subdomain: "profiler-%env(app.secret)%"  # The subdomain for which the profiler will be available
      enabledInProduction: false               # Allow access to the profiler in production mode
