framework:
  # Path to all controllers
  pathWithControllers: app/Controllers

  # Controller namespace
  namespaceForControllers: App\Controllers

  # Show toolbar
  toolbar: true

  # Show toolbar in production mode
  # Note! The page loading speed may decrease if the value is "true"
  toolbarInProduction: false